// Writes src/design/tokens.css from src/design/tokens.json: every colour of both rooms as the sRGB value the gate
// checks (with its OKLCH source in a comment), the collection hues, and the non-colour tokens. The daylight room is
// the default; the lamp-lit room applies with data-theme="lamplit", or with the system's dark preference before a
// choice has been made (the inline script in index.html sets data-theme before the first paint).
//   node scripts/build-tokens.mjs          write the file
//   node scripts/build-tokens.mjs --check  fail if the committed file differs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveRoom } from "./lib/color.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "..", "src", "design", "tokens.json");
const target = join(here, "..", "src", "design", "tokens.css");
const tokens = JSON.parse(readFileSync(source, "utf8"));

const slug = (collection) => collection.split(".")[1];

function roomBlock(room) {
  const spec = tokens.rooms[room];
  const { colours, hues } = resolveRoom(tokens, room);
  const lines = [`  color-scheme: ${spec.scheme};`];
  for (const [name, hex] of Object.entries(colours)) {
    lines.push(`  --c-${name}: ${hex}; /* oklch(${spec.colours[name].join(" ")}) */`);
  }
  for (const [collection, hex] of Object.entries(hues)) {
    lines.push(`  --h-${slug(collection)}: ${hex};`);
  }
  return lines.join("\n");
}

const fixed = `  --s-1: 2px; --s-2: 4px; --s-3: 8px; --s-4: 12px; --s-5: 16px; --s-6: 24px; --s-7: 32px; --s-8: 48px;
  --s-9: 64px; --s-10: 96px;
  --r-control: 3px; --r-panel: 6px;
  --f-reading: "Laminario Sans", system-ui, sans-serif;
  --f-display: "Fraunces", Georgia, serif;
  --f-label: "Courier Prime", "Courier New", monospace;
  --fs-1: 13px; --fs-2: 14px; --fs-3: 16px; --fs-4: 18px; --fs-5: 20px; --fs-6: 24px; --fs-7: 32px; --fs-8: 40px;
  --fs-9: 56px;
  --t-quick: 120ms; --t-move: 240ms; --t-travel: 420ms;
  --ease-out: cubic-bezier(0.2, 0, 0, 1); --ease-in: cubic-bezier(0.3, 0, 1, 1);
  --mm: 3.7795px;`;

const css = `/* Generated by scripts/build-tokens.mjs from tokens.json; do not edit by hand. */
:root {
${fixed}
}

:root,
:root[data-theme="daylight"] {
${roomBlock("daylight")}
  --lift: 0 1px 1px rgb(37 28 22 / 0.12), 0 3px 8px rgb(37 28 22 / 0.10);
  --float: 0 2px 4px rgb(37 28 22 / 0.10), 0 12px 32px rgb(37 28 22 / 0.14);
}

:root[data-theme="lamplit"] {
${roomBlock("lamplit")}
  --lift: inset 0 1px 0 rgb(235 178 95 / 0.18), 0 2px 6px rgb(0 0 0 / 0.5);
  --float: inset 0 1px 0 rgb(235 178 95 / 0.14), 0 16px 40px rgb(0 0 0 / 0.55);
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${roomBlock("lamplit").replace(/^/gm, "  ")}
    --lift: inset 0 1px 0 rgb(235 178 95 / 0.18), 0 2px 6px rgb(0 0 0 / 0.5);
    --float: inset 0 1px 0 rgb(235 178 95 / 0.14), 0 16px 40px rgb(0 0 0 / 0.55);
  }
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --t-quick: 0ms; --t-move: 0ms; --t-travel: 0ms;
  }
}
`;

if (process.argv.includes("--check")) {
  const current = readFileSync(target, "utf8");
  if (current !== css) {
    console.error("src/design/tokens.css differs from tokens.json: run node scripts/build-tokens.mjs");
    process.exit(1);
  }
  console.log("tokens.css matches tokens.json");
} else {
  writeFileSync(target, css);
  console.log(`wrote ${target}`);
}
