#!/usr/bin/env python3
"""Write ``docs/collections/tree.md``: every node of the collection tree with its names, description and rule.

Generated from ``app/collections/data/tree.yaml`` and the taxa lock, so the page cannot drift from the tree the
product serves; CI fails when the committed page differs (``--check``). Needs PyYAML only.

    python scripts/render_tree_docs.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.collections import vocab  # noqa: E402
from app.collections.tree import Node, Tree, counts, load_tree  # noqa: E402

OUT = ROOT / "docs" / "collections" / "tree.md"
GBIF = "https://www.gbif.org/species/"


def _names(tree: Tree) -> dict[int, str]:
    return {v["key"]: f"{v['name']} ({v['rank']})" for v in tree.taxa.values()}


def rule_text(node: Node, tree: Tree) -> str:
    if node.is_view:
        return "view: slides whose host lies inside the collection"
    names = _names(tree)
    parts_vocab = vocab.load().parts
    alternatives = []
    for c in node.rule.clauses:
        bits = []
        if c.kinds and not c.taxa:
            bits.append(" or ".join(sorted(c.kinds)))
        if c.taxa:
            bits.append(", ".join(f"[{names[k]}]({GBIF}{k})" for k in c.taxa))
        if c.exclude:
            bits.append("not " + ", ".join(f"[{names[k]}]({GBIF}{k})" for k in c.exclude))
        if c.paths:
            bits.append("path " + ", ".join(f"`{p}`" for p in c.paths))
        if c.parts:
            bits.append("part: " + ", ".join(parts_vocab[p]["en"].lower() for p in sorted(c.parts)))
        if c.preservation:
            bits.append(", ".join(sorted(s.replace("_", " ") for s in c.preservation)))
        alternatives.append("; ".join(bits))
    text = " **or** ".join(a for a in alternatives if a) or "what its children take"
    if node.is_container and text != "what its children take":
        text += "; takes what its children take"
    if node.rule.priority:
        text += f" (priority {node.rule.priority})"
    return text


def render() -> str:
    tree = load_tree()
    c = counts(tree)
    lines = [
        "# The collection tree",
        "",
        "Generated by `scripts/render_tree_docs.py` from `app/collections/data/tree.yaml` and the taxa lock; do not",
        "edit by hand. The model and the rule semantics are in the wiki page",
        "[09 The collection tree](../architecture/09_collections.md).",
        "",
        f"{c['realm']} realms, {c['collection']} collections, {c['sub-collection and group']} sub-collections and "
        f"groups (the ten vertebrate organ systems counted once), {sum(1 for _ in tree.walk())} nodes in all. "
        "Taxa link to their GBIF backbone page.",
        "",
    ]
    for realm in tree.roots:
        lines += [f"## {realm.name['en']} / {realm.name['es']}", "", f"`{realm.id}` · {rule_text(realm, tree)}", "",
                  realm.about["en"], "", f"*{realm.about['es']}*", ""]
        for collection in realm.children:
            lines += [f"### {collection.name['en']} / {collection.name['es']}", "",
                      f"`{collection.id}` · {rule_text(collection, tree)}", "", collection.about["en"], "",
                      f"*{collection.about['es']}*", ""]
            if collection.children:
                lines += ["| Node | EN | ES | Rule |", "|---|---|---|---|"]
                for node in collection.children:
                    for n in [node, *node.children]:
                        indent = "&nbsp;&nbsp;&nbsp;" if n is not node else ""
                        lines.append(f"| {indent}`{n.id.removeprefix(collection.id + '.')}` | {n.name['en']} | "
                                     f"{n.name['es']} | {rule_text(n, tree)} |")
                lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run scripts/render_tree_docs.py")
            return 1
        print("tree docs: OK")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
