"""The coverage matrix: how many base-collection slides sit at or under every node of the collection tree.

``docs/collections/coverage.md`` is written from ``data/base/lock.yaml`` and the tree: one table per collection, a
row per sub-collection and group in tree order, with the slides placed there or below. A node with no slide is marked
open for contribution (dossier 06, section 4: a sub-collection without an open candidate is shown honestly as open),
and a view node (the host relations of the vertebrate collections) is listed with the slides it shows rather than
slides placed in it. The file is generated by ``python -m app.base validate``; it is never edited by hand.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

import yaml

from app.base.lock import LOCK
from app.collections.tree import Node, Tree, load_tree

ROOT = Path(__file__).resolve().parent.parent.parent
COVERAGE = ROOT / "docs" / "collections" / "coverage.md"


def counts(slides: list[dict], tree: Tree) -> dict[str, int]:
    """Slides placed at each node or any of its descendants."""
    placed = Counter(s["placement"]["node"] for s in slides)
    out: dict[str, int] = {}

    def total(node: Node) -> int:
        n = placed.get(node.id, 0) + sum(total(c) for c in node.children)
        out[node.id] = n
        return n

    for root in tree.roots:
        total(root)
    return out


def _rows(node: Node, depth: int, per: dict[str, int]) -> list[str]:
    out = []
    for child in node.children:
        indent = "&nbsp;&nbsp;" * depth
        if child.is_view:
            out.append(f"| {indent}{child.name['en']} | view | shows slides by host |")
            continue
        n = per.get(child.id, 0)
        out.append(f"| {indent}{child.name['en']} (`{child.id.split('.', 2)[-1]}`) | {child.level} | "
                   f"{n if n else 'open for contribution'} |")
        out += _rows(child, depth + 1, per)
    return out


def write(slides: list[dict] | None = None, target: Path = COVERAGE) -> dict[str, int]:
    tree = load_tree()
    if slides is None:
        slides = yaml.safe_load(LOCK.read_text(encoding="utf-8"))["slides"]
    per = counts(slides, tree)
    lines = [
        "# The base collection: coverage per collection and sub-collection",
        "",
        "Generated by `python -m app.base validate` from `data/base/lock.yaml` and the collection tree; do not edit by "
        "hand. Each count is the slides placed at the node or below it. A node with none is open for contribution: "
        "no open, licence-compatible candidate was found for it when the base collection was curated.",
        "",
        f"Slides: **{len(slides)}**. Nodes with at least one slide: "
        f"**{sum(1 for n in tree.nodes.values() if per.get(n.id) and not n.is_view)}** of "
        f"{sum(1 for n in tree.nodes.values() if not n.is_view)}.",
        "",
    ]
    for realm in tree.roots:
        lines += [f"## {realm.name['en']} ({per.get(realm.id, 0)})", ""]
        for collection in realm.children:
            lines += [f"### {collection.name['en']} (`{collection.id}`): {per.get(collection.id, 0)}", "",
                      "| Node | Level | Slides |", "|---|---|---|"]
            placed_here = sum(1 for s in slides if s["placement"]["node"] == collection.id)
            if placed_here:
                lines.append(f"| {collection.name['en']} (the collection itself) | collection | {placed_here} |")

            lines += _rows(collection, 0, per)
            lines.append("")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return per
